baseURL = "https://0az.github.io"
title = "0az"

languageCode = "en-us"
defaultcontentlanguage = "en-us"

theme = "hugo-coder"

paginate = 20
canonifyurls = true

disableKinds = ["taxonomy","taxonomyTerm"]

publishDir = "0az.github.io"

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Andrew Zhou"
    info = "Software Engineer and Student"
    description = "Andrew's Personal Website"
    keywords = "blog,developer,personal"
    # avatarurl = "images/avatar.jpg"

    # favicon_32 = "/img/favicon-32x32.png"
    # favicon_16 = "/img/favicon-16x16.png"

    # footercontent = "Enter a text here."
    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/0az/"
[[params.social]]
	name = "LinkedIn"
	icon = "fab fa-linkedin-in"
	weight = 2
	url = "https://linkedin.com/in/afzhou/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/afzhou/"
# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
# [[menu.main]]
#     name = "Résumé"
#     weight = 3
#     url = ""
